#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Crypt-DES_EEE3
version:      0.01
version_from: lib/Crypt/DES_EEE3.pm
installdirs:  site
requires:
    Crypt::DES:                    0
    Crypt::DES_EDE3:               0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
